// workspaces/liferay-marketplace-workspace/client-extensions/liferay-marketplace-custom-element/src/main.tsx
/**
 * SPDX-FileCopyrightText: (c) 2000 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

import {Root, createRoot} from 'react-dom/client';

import AppRoutes, {RouteType} from './Routes';

import './main.scss';
import Providers from './providers';

class WebComponent extends HTMLElement {
	private root: Root | undefined;

	connectedCallback() {
		if (!this.root) {
			this.root = createRoot(this);

			this.root.render(
				<Providers
					properties={{
						cloudBaseURL: this.getAttribute('cloudBaseURL') || '',
						contactSupportUrl:
							this.getAttribute('contactSupportUrl') || '',
						eulaBaseURL: this.getAttribute('eulaBaseURL') || '',
						marketoFormId: this.getAttribute('marketoFormId') || '',
					}}
				>
					<AppRoutes path={this.getAttribute('path') as RouteType} />
				</Providers>
			);
		}
	}
}
const ELEMENT_ID = 'liferay-marketplace-custom-element';

if (!customElements.get(ELEMENT_ID)) {
	customElements.define(ELEMENT_ID, WebComponent);
}

// workspaces/liferay-aihub-workspace/client-extensions/liferay-aihub-custom-element/src/index.tsx
/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

import React from 'react';
import {createRoot} from 'react-dom/client';

import ChatbotWidget from './components/ChatbotWidget';
import {WidgetConfiguration} from './types';

import './index.css';

const CHATBOT_WIDGET_ID = 'aihub-chatbot-widget';

if (!document.getElementById(CHATBOT_WIDGET_ID)) {
	const scriptTag = document.getElementById('aihub-chatbot-widget-script');

	if (!scriptTag) {
		console.error(
			'Element with id="aihub-chatbot-widget-script" not found'
		);
	}
	else {
		const widgetConfiguration: WidgetConfiguration = {
			chatbotExternalReferenceCode:
				scriptTag.getAttribute('chatbot-external-reference-code') || '',
		};

		const element = document.createElement('div');

		element.id = CHATBOT_WIDGET_ID;

		document.body.appendChild(element);

		createRoot(element).render(
			<ChatbotWidget widgetConfiguration={widgetConfiguration} />
		);
	}
}
